### ISSUE TITLE
questions for the program running

### ISSUE THREAD

**Issue by emozhishou** [artperrin/image2csv#4]
I am a new learner.
I have cloned the project and run it on the prcharm via anaconda environments.
I didnot know which file should be employed and can get the result.
I run the grid_detector.py, where have "main" function , but just output the figure.

**Comment by artperrin** [comment]
Hi! The main script is the `image2csv.py` file, and it needs arguments to be run.
I am not a PyCharm user, also I've found this tutorial on YouTube which can help you running scripts with arguments: https://www.youtube.com/watch?v=Byta5WkeNiA
Otherwise, you can run the program using a command prompt (cmd for example if you are on Windows) following these steps:

1. Open the command prompt and go to the project's directory: ```$ cd path/to/directory``` ;
2. Then you have to activate you virtual environment if you're using one: ```$ venv/Scripts/activate``` ;
3. Now you must install all the requirements if never done before: ```$ pip install -r requirements.txt``` ;
4. Only then you will be able to run the main program, with the command line: ```$ python image2csv.py -i path/to/image```.

In the last command line, ```-i``` is the keyword to specify the image argument, it is required. There are optionnal arguments, which are described if you write the command line: ```$ python image2csv.py -h```.
An example with a test image would be: ```$ python image2csv.py -i ./testimages/test.png```.

I hope you'll find it useful ! :wink:

**Comment by artperrin** [comment]
Feel free to re-open this issue if needed !
