### ISSUE TITLE
{Question} Any Idea to Make it work on this image

### ISSUE THREAD

**Issue by ilovefreesw** [artperrin/image2csv#5]
I have this image from which I want to extract text:

![image](https://user-images.githubusercontent.com/77317006/135215567-51ffac40-1cd3-4672-8888-11f5d74704d9.png)

This tool is not seem to be working on this. I don't know what to do. It generates the following output.

![Screenshot from 2021-09-28 15-25-24](https://user-images.githubusercontent.com/77317006/135065627-5045a926-1616-43c5-9d3f-fd2127f652bd.png)

Do you have any idea how to fix this. Thanks.

**Comment by artperrin** [comment]
Hi,
There are many (strong) hypotheses I've made for this `image2csv` program to work as supposed to, thus making it a "case study" for me more than a powerful tool for the community to use.
In fact, with the input image you have, you can't use automatic grid detection (as the grid is not visible) neither can you use the "manual grid" workflow as your columns' width are not the same from one another. In addition, I chose a `tesseract` setting to perform number detection, and not text. For all these reasons, the output you get is total nonsense.
To be honest, I think the code needs proper corrections for the tool to be really usable, and I'm afraid your usage requires a great amount of work rather than a small bug fix.
I suggest you try a more robust and professionnal OCR app, or you can fork this repository and improve the program. 😉
